
spring:
  application:
    name: book-client
  cloud:
    config:
      discovery:
        enabled: true
        service-id: config-server

  data:
    mongodb:
      uri: mongodb://localhost:27017/gallerydb

#book-service:
#  url: http://localhost:8084/data

server:
  port: 8082

eureka:
  client:

    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
    eureka-server-d-n-s-name: book-client
  instance:
    preferIpAddress: true
