spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: zuul-service
  cloud:
    config:
      discovery:
        enabled: true
        service-id: config-server

server:
  port: 8766

eureka:
  client:
    fetch-registry: true
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true
    lease-renewal-interval-in-seconds: 30

feign.hystrix.enabled: false

zuul:
  routes:
    book-client:
      path: /client/**
      service-id: BOOK-CLIENT

# Increase the Hystrix timeout to 60s (globally)
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000

ribbon:
  ReadTimeout=60000:

#spring:   # for spring-gateway
#  cloud:
#    gateway:
#      routes:
#        - id: per_route_timeouts
#        uri: https://example.org
#        predicates:
#           - names: Path
#             args:
#              pattern: /delay/{timeout}
#        metadata:
#          response-timeout: 200
#          connect-timeout: 200
